# Generated by Django 4.2.7 on 2023-12-07 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='title',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
